'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {apiGet} from '@/lib/api';
function ago(v){if(!v)return 'No recent observation';const s=Math.max(0,(Date.now()-new Date(v).getTime())/1000);if(s<3600)return Math.max(1,Math.floor(s/60))+' min ago';if(s<86400)return Math.floor(s/3600)+' hours ago';return Math.floor(s/86400)+' days ago'}
function dest(a){if(a.type==='setup_incomplete')return `/dashboard/mps/${a.tenant_id}/setup`;if(a.type?.startsWith('whatsapp'))return '/dashboard/system/whatsapp';if(a.type?.startsWith('job_'))return '/dashboard/system/jobs';return a.tenant_id?`/dashboard/mps/${a.tenant_id}`:'/dashboard/system/health'}
export default function DashboardOverview(){
 const [stats,setStats]=useState(null),[accounts,setAccounts]=useState([]),[alerts,setAlerts]=useState([]),[health,setHealth]=useState(null),[errors,setErrors]=useState({});
 const load=useCallback(async(k,p,fn)=>{try{const r=await apiGet(p);fn(r)}catch(e){setErrors(x=>({...x,[k]:true}))}},[]);
 useEffect(()=>{load('stats','/api/admin/stats',setStats);load('accounts','/api/admin/mps',r=>setAccounts(r.mps||[]));load('alerts','/api/admin/alerts',r=>setAlerts(r.alerts||[]));load('health','/api/admin/system-health',setHealth)},[load]);
 const sorted=useMemo(()=>[...alerts].sort((a,b)=>({critical:0,error:0,warning:1,info:2}[a.severity]??3)-({critical:0,error:0,warning:1,info:2}[b.severity]??3)),[alerts]);
 const critical=alerts.filter(a=>a.severity==='critical'||a.severity==='error').length,pending=alerts.length-critical,total=stats?.total_accounts??stats?.total_mps??accounts.length;
 const configured=[health?.whatsapp?.status,health?.openai?.status,health?.gemini?.status].filter(Boolean),healthy=configured.length?Math.round(configured.filter(x=>x==='green').length/configured.length*100):null;
 const services=[['API / AI services',health?.openai?.status,health?.openai?.configured?'Configured':'Configuration unavailable'],['WhatsApp Service',health?.whatsapp?.status,health?.whatsapp?.reason||'Messaging status'],['Gemini Processing',health?.gemini?.status,health?.gemini?.configured?'Configured':'Configuration unavailable']];
 return <div className="ref-dashboard">
  <div className="ref-welcome"><div><h1>Good morning{accounts.some(a=>a.display_name==='Sanket Jadhav')?', Sanket':''}</h1><p>Here’s what needs your attention today.</p></div><div className="ref-date">{new Date().toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short',year:'numeric'})}<span>·</span>{new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</div></div>
  <div className="ref-kpis">
   <div className="ref-kpi red"><i>!</i><div><strong>{errors.alerts?'—':critical}</strong><b>Critical Issues</b><small>{critical?'Requires attention':'No critical issues'}</small></div><span>⌁</span></div>
   <div className="ref-kpi amber"><i>◷</i><div><strong>{errors.alerts?'—':pending}</strong><b>Pending Actions</b><small>{pending?'Open operational items':'Queue clear'}</small></div><span>⌁</span></div>
   <div className="ref-kpi green"><i>✓</i><div><strong>{healthy===null?'—':healthy+'%'}</strong><b>Platform Health</b><small>{healthy===100?'All monitored systems operational':'Review service health'}</small></div><span>⌁</span></div>
   <div className="ref-kpi blue"><i>♙</i><div><strong>{errors.accounts?'—':total}</strong><b>Active Accounts</b><small>Current customer registry</small></div><span>⌁</span></div>
  </div>
  <div className="ref-main-grid">
   <section className="ref-card ref-queue"><header><h2>Action Queue <em>{alerts.length}</em></h2><Link href="/dashboard/system/health">View all →</Link></header><div className="ref-table-head"><span>Issue</span><span>Account / Context</span><span>Severity</span><span>Action</span></div>{sorted.slice(0,5).map((a,i)=><div className="ref-action" key={i}><span className={'ref-action-icon '+(a.severity||'info')}>!</span><span><b>{a.title}</b><small>{a.description}</small></span><span>{a.tenant_id?'Account #'+a.tenant_id:'System'}</span><span><mark className={a.severity||'info'}>{a.severity||'Review'}</mark></span><Link href={dest(a)}>View</Link></div>)}{!alerts.length&&!errors.alerts&&<div className="ref-empty">No active operational alerts.</div>}{errors.alerts&&<div className="ref-empty">Action queue data unavailable.</div>}</section>
   <div className="ref-right-stack">
    <section className="ref-card"><header><h2>Platform Health</h2><Link href="/dashboard/system/health">View details →</Link></header><div className="ref-services">{services.map(([n,s,d])=><div key={n}><span className={'ref-dot '+(s||'unknown')}></span><b>{n}</b><em>{s==='green'?'Operational':s==='red'?'Needs attention':'Unknown'}</em><small>{d}</small></div>)}</div></section>
    <section className="ref-card"><header><h2>Recent Activity</h2><Link href="/dashboard/staff-access/audit">View all →</Link></header><div className="ref-activity"><div><i>◉</i><span><b>Operational activity</b><small>Use Audit Log for the verified event history.</small></span></div><div><i>✓</i><span><b>Latest health observation</b><small>{health?.last_checked?ago(health.last_checked):'No timestamp available'}</small></span></div></div></section>
   </div>
  </div>
  <div className="ref-bottom-grid">
   <section className="ref-card ref-trends"><header><h2>Case Overview</h2><Link href="/dashboard/cases-intelligence/analytics">View analytics →</Link></header><div className="ref-chart-placeholder"><div className="ref-chart-line"></div><p>Trend series is not exposed by the current Admin summary API.</p></div><div className="ref-mini-stats"><div><b>{stats?.total_cases??'—'}</b><span>Total Cases</span></div><div><b>{stats?.resolved_cases??'—'}</b><span>Resolved</span></div><div><b>{stats?.pending_cases??'—'}</b><span>Pending</span></div></div></section>
   <section className="ref-card ref-account"><header><h2>Account Status</h2><Link href="/dashboard/accounts">View all →</Link></header><div className="ref-donut"><div><strong>{total}</strong><small>Total Accounts</small></div></div><div className="ref-account-legend"><span><i></i>Customer accounts <b>{total}</b></span><span><i></i>Needs setup <b>{accounts.filter(a=>(a.completeness||0)<70).length}</b></span><span><i></i>Missing WhatsApp <b>{accounts.filter(a=>!a.whatsapp_number||String(a.whatsapp_number).startsWith('temp_')).length}</b></span></div></section>
   <section className="ref-card ref-wa"><header><h2>WhatsApp Operations</h2><Link href="/dashboard/system/whatsapp">View details →</Link></header><div className="ref-wa-stats"><div><b>{health?.whatsapp?.status==='green'?'Operational':'Review'}</b><span>Service</span></div><div><b>{health?.whatsapp?.last_webhook?ago(health.whatsapp.last_webhook):'—'}</b><span>Last webhook</span></div></div><div className="ref-bars">{[7,10,8,12,9,14,13,16,12,18,15,17,14,19,16,13,18,15,12,17].map((h,i)=><i key={i} style={{height:(h*3)+'px'}}></i>)}</div><small className="ref-chart-note">Decorative activity baseline; open WhatsApp Operations for verified message counts.</small></section>
  </div>
  <footer className="ref-footer"><span>◢</span><em>Technology for a more responsive democracy.</em><b>Needle</b></footer>
 </div>
}