[pytest]
addopts = -p no:langsmith
filterwarnings =
    ignore:Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater:UserWarning:langsmith.schemas
    ignore:'_UnionGenericAlias' is deprecated:DeprecationWarning:google.genai.types
    ignore:The default datetime adapter is deprecated as of Python 3.12:DeprecationWarning:sqlalchemy.engine.default
    ignore:(?s).*on_event is deprecated.*:DeprecationWarning:main
    ignore:(?s).*on_event is deprecated.*:DeprecationWarning:fastapi.applications
