import json

# --- THE MASTER DATASET (Budget 2025-26 Enriched) ---
DATA = [
    {
        "Scheme": "Pradhan Mantri KISAN Samman Nidhi (PM-KISAN)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To provide income support to all landholding farmers' families to supplement their financial needs.",
        "Focus": ["Financial Assistance"],
        "Budget_Alloc": "₹60,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To provide insurance coverage and financial support to farmers in the event of crop failure.",
        "Focus": ["Financial Assistance"],
        "Budget_Alloc": "₹12,242 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Sustainable Rooftop Implementation for Solar Transfiguration of India (SRISTI)",
        "Ministry": "Ministry of Power",
        "Description": "Provide incentives for installing rooftop solar power plant projects.",
        "Focus": ["General"],
        "Budget_Alloc": "₹20,000 Cr (PM Surya Ghar)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Extension of Phase-II of Grid Connected Rooftop Solar programme",
        "Ministry": "Ministry of New and Renewable Energy",
        "Description": "Extend the Grid Connected Rooftop Solar programme Phase-II until 31.03.2026 without additional financial application.",
        "Focus": ["General"],
        "Budget_Alloc": "₹20,000 Cr (PM Surya Ghar)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Solarisation of Sun-Temple Town of Modhera, Gujarat",
        "Ministry": "Ministry of New and Renewable Energy",
        "Description": "Achieve 100% solarization of Modhera, fulfilling domestic and agricultural electricity needs through solar energy and setting up a pilot project for a village or town running entirely on solar power.",
        "Focus": ["General"],
        "Budget_Alloc": "₹20,000 Cr (PM Surya Ghar)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Production Linked Incentive Scheme (Tranche II) under National Programme on High Efficiency Solar PV Modules",
        "Ministry": "Ministry of New and Renewable Energy",
        "Description": "Allocate 39600 MW of domestic Solar PV module manufacturing capacity with an outlay of Rs. 14007 crore, expected to generate significant employment and become operational in phases from October 2024 to April 2026.",
        "Focus": ["General"],
        "Budget_Alloc": "₹20,000 Cr (PM Surya Ghar)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Clarification on applicability of central financial assistance under Rooftop Solar Programme Phase-II",
        "Ministry": "Ministry of New and Renewable Energy",
        "Description": "Clarify the applicability of central financial assistance for solar systems installed under the Virtual Net Metering arrangement.",
        "Focus": ["General"],
        "Budget_Alloc": "₹20,000 Cr (PM Surya Ghar)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Development of Solar Parks and Ultra Mega Solar Power Projects",
        "Ministry": "Ministry of New and Renewable Energy",
        "Description": "Extend the Solar Park Scheme timeline until FY 2025-26, facilitating the development of solar parks and ultra mega solar power projects without additional financial implications.",
        "Focus": ["General"],
        "Budget_Alloc": "₹20,000 Cr (PM Surya Ghar)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Poshan Abhiyaan",
        "Ministry": "Ministry of Women and Child Development",
        "Description": "To improve nutritional outcomes for children, pregnant women, and lactating mothers.",
        "Focus": ["Health and Nutrition"],
        "Budget_Alloc": "₹21,960 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Samagra Shiksha",
        "Ministry": "Ministry of Education",
        "Description": "To ensure inclusive and equitable quality education from pre-school to senior secondary stage.",
        "Focus": ["General"],
        "Budget_Alloc": "₹41,250 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Jal Jeevan Mission (JJM)",
        "Ministry": "Ministry of Jal Shakti",
        "Description": "To provide safe and adequate drinking water through individual household tap connections by 2024 to all households in rural India.",
        "Focus": ["General"],
        "Budget_Alloc": "₹67,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Ayushman Bharat",
        "Ministry": "Ministry of Health and Family Welfare",
        "Description": "To provide health coverage of Rs. 5 lakh per family per year for secondary and tertiary care hospitalization.",
        "Focus": ["FINANCIAL ASSISTANCE "],
        "Budget_Alloc": "₹9,406 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Health Mission (NHM)",
        "Ministry": "Ministry of Health and Family Welfare",
        "Description": "To provide accessible, affordable, and quality health care to the rural population, especially the vulnerable groups.",
        "Focus": ["INFRASTRUCTURE DEVELOPMENT"],
        "Budget_Alloc": "₹37,227 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Urban Health Mission (NUHM)",
        "Ministry": "Ministry of Health and Family Welfare",
        "Description": "To address health concerns of the urban poor by facilitating equitable access to quality healthcare services.",
        "Focus": ["PROGRAMME"],
        "Budget_Alloc": "₹37,227 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Awas Yojana (Urban) (PMAY-U)",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To provide housing for all urban poor by 2022.",
        "Focus": ["General"],
        "Budget_Alloc": "₹23,294 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Urban Health Mission (NUHM)",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To improve the health status of the urban population.",
        "Focus": ["General"],
        "Budget_Alloc": "₹37,227 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To provide at least 100 days of wage employment in a financial year to every rural household.",
        "Focus": ["General"],
        "Budget_Alloc": "₹86,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Awaas Yojana - Gramin (PMAY-G)",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To provide housing for the rural poor by 2022.",
        "Focus": ["General"],
        "Budget_Alloc": "₹23,294 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To provide comprehensive insurance coverage to farmers against crop failure.",
        "Focus": ["General"],
        "Budget_Alloc": "₹12,242 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To provide income support to all landholding farmers' families to supplement their financial needs.",
        "Focus": ["General"],
        "Budget_Alloc": "₹60,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "MGNREGA Social Audit",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To ensure transparency and accountability in the implementation of MGNREGA through social audits.",
        "Focus": ["General"],
        "Budget_Alloc": "₹86,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "MGNREGA GeoMGNREGA",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To use geospatial technology to improve planning and implementation of MGNREGA works.",
        "Focus": ["General"],
        "Budget_Alloc": "₹86,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Livelihoods in Full Employment (LIFE) under MGNREGA",
        "Ministry": "Ministry of Housing and Urban Affairs",
        "Description": "To enhance the livelihood opportunities of MGNREGA workers by providing skill development training.",
        "Focus": ["General"],
        "Budget_Alloc": "₹86,000 Cr",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Faster Adoption and Manufacturing of \n(Hybrid and) Electric Vehicles in India \n(FAME-India) Scheme",
        "Ministry": "Ministry of Heavy Industries",
        "Description": "This scheme aims to promote the adoption of electric and \nhybrid vehicles in India.",
        "Focus": ["Manufacturing Support"],
        "Budget_Alloc": "₹4,000 Cr (PM E-DRIVE)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Production Linked Incentive (PLI) Scheme \nfor Automobile and Auto Components",
        "Ministry": "Ministry of Heavy Industries",
        "Description": "The PLI scheme provides financial incentives to boost domestic \nmanufacturing of advanced automotive technology products.",
        "Focus": ["Financial Assistance"],
        "Budget_Alloc": "₹19,000 Cr (Total)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Production Linked Incentive (PLI) Scheme \nfor Advanced Chemistry Cell (ACC) Battery \nStorage",
        "Ministry": "Ministry of Heavy Industries",
        "Description": "To enhance India's manufacturing capabilities for ACC batteries.",
        "Focus": ["Manufacturing Support"],
        "Budget_Alloc": "₹19,000 Cr (Total)",
        "Budget_Status": "🟢 Active",
        "Budget_Note": "2025-26 Budget Allocation",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Krishi Sinchai Yojana (PMKSY)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To enhance irrigation coverage and improve water use efficiency in a focused manner.",
        "Focus": ["Agricultural Development and Sustainability"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Kisan Maan-Dhan Yojana (PM-KMY)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To provide social security to small and marginal farmers in their old age.",
        "Focus": ["Financial Assistance"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Krishi Kalyan Abhiyan",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To aid, assist and advise farmers on the best agricultural practices and enhance their incomes.",
        "Focus": ["Agricultural Development and Sustainability"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Soil Health Cards (SHC) Scheme",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To promote soil test-based and balanced use of fertilizers to enable farmers to realize higher yields.",
        "Focus": ["Agricultural Development and Sustainability"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Bamboo Mission",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To promote the growth of the bamboo sector through area-based, regionally differentiated strategy.",
        "Focus": ["Infrastructure"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Green Revolution – Krishonnati Yojana",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To develop the agriculture and allied sectors in a holistic and sustainable manner.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Yuva Sahakar-Cooperative Enterprise Support and Innovation Scheme",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To encourage cooperatives to take up innovative ventures for socio-economic development.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pradhan Mantri Annadata Aay SanraksHan Abhiyan (PM-AASHA)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To ensure remunerative prices to the farmers for their produce.",
        "Focus": ["Support and protection"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Paramparagat Krishi Vikas Yojana (PKVY)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To promote organic farming and improve soil health.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Food Security Mission (NFSM)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To increase the production of rice, wheat, pulses, coarse cereals, and commercial crops.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Pandit Deen Dayal Upadhyay Unnat Krishi Shiksha Yojana (PDDUUKSY)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To promote agricultural education and research in the country.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "Rashtriya Gokul Mission (RGM)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To develop and conserve indigenous bovine breeds for improving their genetic makeup and increasing the milk production.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Beekeeping and Honey Mission (NBHM)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To promote holistic growth of the beekeeping industry for income and employment generation.",
        "Focus": ["Agricultural Development and Sustainability"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    },
    {
        "Scheme": "National Mission on Edible Oils (NMEO-OP)",
        "Ministry": "Ministry of Agriculture & Farmers Welfare",
        "Description": "To augment the availability of edible oils and reduce import dependence through the promotion of oilseed cultivation.",
        "Focus": ["Education and Training"],
        "Budget_Alloc": "Check Dept",
        "Budget_Status": "Unknown",
        "Budget_Note": "",
        "Grant": "Refer to Guidelines",
        "Eligibility": "Check Official Portal",
        "Documents": "Standard KYC",
        "Process": "Online/District Office"
    }
]

def create_db_file():
    print(f"🚀 Writing {len(DATA)} schemes to 'schemes.json'...")
    with open("schemes.json", "w", encoding='utf-8') as f:
        json.dump(DATA, f, indent=4, ensure_ascii=False)
    print("✅ Success! 'schemes.json' created with Hardcoded Data.")

if __name__ == "__main__":
    create_db_file()